
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftBICONDleftIMPLIESleftORleftANDrightNOTAND BICOND CONST IMPLIES LPAREN NOT OR RPAREN VARformula : VARformula : CONSTformula : NOT formulaformula : formula AND formula\n               | formula OR formula\n               | formula IMPLIES formula\n               | formula BICOND formulaformula : LPAREN formula RPAREN'
    
_lr_action_items = {'VAR':([0,4,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'CONST':([0,4,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'NOT':([0,4,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'LPAREN':([0,4,5,6,7,8,9,],[5,5,5,5,5,5,5,]),'$end':([1,2,3,10,12,13,14,15,16,],[0,-1,-2,-3,-4,-5,-6,-7,-8,]),'AND':([1,2,3,10,11,12,13,14,15,16,],[6,-1,-2,-3,6,-4,6,6,6,-8,]),'OR':([1,2,3,10,11,12,13,14,15,16,],[7,-1,-2,-3,7,-4,-5,7,7,-8,]),'IMPLIES':([1,2,3,10,11,12,13,14,15,16,],[8,-1,-2,-3,8,-4,-5,-6,8,-8,]),'BICOND':([1,2,3,10,11,12,13,14,15,16,],[9,-1,-2,-3,9,-4,-5,-6,-7,-8,]),'RPAREN':([2,3,10,11,12,13,14,15,16,],[-1,-2,-3,16,-4,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,4,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> VAR','formula',1,'p_formula_var','proyecto.py',52),
  ('formula -> CONST','formula',1,'p_formula_const','proyecto.py',56),
  ('formula -> NOT formula','formula',2,'p_formula_not','proyecto.py',60),
  ('formula -> formula AND formula','formula',3,'p_formula_binop','proyecto.py',64),
  ('formula -> formula OR formula','formula',3,'p_formula_binop','proyecto.py',65),
  ('formula -> formula IMPLIES formula','formula',3,'p_formula_binop','proyecto.py',66),
  ('formula -> formula BICOND formula','formula',3,'p_formula_binop','proyecto.py',67),
  ('formula -> LPAREN formula RPAREN','formula',3,'p_formula_paren','proyecto.py',71),
]
